# Config file for automatic testing at travis-ci.org
language: python
jobs:
  include:
    - name: "Python 3.6 on Linux"
      os: linux
      dist: xenial
      language: python
      python: 3.6
      env: python_version=3.6

    - name: "Python 3.7 on Linux"
      os: linux
      dist: xenial
      language: python
      python: 3.7
      env: python_version=3.7

    - name: "Python 3.8 on Linux"
      os: linux
      dist: focal
      language: python
      python: 3.8
      env: python_version=3.8

    - name: "Python 3.9 on Linux"
      os: linux
      dist: focal
      language: python
      python: 3.9
      env: python_version=3.9

    - name: "Python 3.10 on Linux"
      os: linux
      dist: focal
      language: python
      python: 3.10-dev
      env: python_version=3.10-dev

    - name: "Python 3.11 on Linux"
      os: linux
      dist: focal
      language: python
      python: 3.11-dev
      env: python_version=3.11-dev

  allow_failures:
    - python: 3.11-dev
    - python: 3.10-dev

cache:
  directories:
    - eggs
install:
  - pip install -U pip
  - pip install -e .[test]
  - pip install codecov
  - sleep 1
script:
  - make clean
  - make lint
  - mypy fhir/resources/
  - black --check --verbose --exclude 'fhir/resources/DSTU2/tests/' fhir/resources/
  - pytest tests
  - pytest fhir/resources/DSTU2/tests
  - pytest fhir/resources/STU3/tests
  - pytest -s --cov=fhir/resources/tests -s --tb=native -v --cov-report term-missing --cov-append fhir/resources/tests
after_success:
  - codecov
